version: "3.9"

services:
  api:
    build: ./Pangolivia.API
    container_name: pangolivia-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      # Use Development so Swagger is available; flip to Production later
      ASPNETCORE_ENVIRONMENT: "Development"
      # Local dev DB from the host machine (SQL Server on port 1433)
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=Pangolivia;User Id=sa;Password=Password123;TrustServerCertificate=True;"
    # If you want logs persisted:
    # volumes:
    #   - ./Pangolivia.API/logs:/app/logs

  web:
    build: ./Pangolivia.Next
    container_name: pangolivia-web
    ports:
      - "3000:3000"
    environment:
      # Next.js will proxy to the API container by its service name
      NEXT_PUBLIC_API_BASE: "http://api:8080"
    depends_on:
      - api
