# name: Deploy to Azure

# on:
#   push:
#     branches: [ main, feat/cicd-update ]
# permissions:
#   id-token: write
#   contents: read

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Azure login
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       # After Azure login
#       - name: Debug Azure Login
#         run: |
#           az account show
#           az acr list --output table

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       # Login
#       - name: ACR login
#         run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

#       # Build and push API
#       - name: Build and push API
#         uses: docker/build-push-action@v5
#         with:
#           context: ./Pangolivia.API
#           push: true
#           tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/api:latest
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#       # Deploy API first
#       - name: Deploy API to Azure Container Apps
#         uses: azure/container-apps-deploy-action@v1
#         with:
#           resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
#           containerAppName: ${{ vars.API_APP_NAME }}
#           imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/api:latest
#           environmentVariables: |
#             ConnectionStrings__Connection=${{ secrets.DB_CONNECTION_STRING }}

#       # Get API URL
#       - name: Get API URL
#         run: |
#           API_URL=$(az containerapp show -n ${{ vars.API_APP_NAME }} -g ${{ secrets.AZURE_RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
#           echo "VITE_API_URL=https://$API_URL/api" >> "$GITHUB_ENV"
      
#       # After setting API URL
#       - name: Debug API URL
#         run: echo "API URL is ${{ env.VITE_API_URL }}"

#       # Build and push frontend with API URL
#       - name: Build and push frontend
#         uses: docker/build-push-action@v5
#         with:
#           context: ./Pangolivia.Frontend
#           push: true
#           tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:latest
#           build-args: |
#             VITE_API_URL=${{ env.VITE_API_URL }}
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#       # Deploy frontend
#       - name: Deploy Frontend to Azure Container Apps
#         uses: azure/container-apps-deploy-action@v1
#         with:
#           resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
#           containerAppName: ${{ vars.FRONTEND_APP_NAME }}
#           imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:latest